'use client';
import { useEffect,useState } from 'react';
import { defaultTournament,stageOrder,type MatchStage,type Tournament } from '@/lib/tournament';
type EditorRow={email:string;addedAt:string};
export default function AdminPanel({editor,isOwner}:{editor:string;isOwner:boolean}){
 const [data,setData]=useState<Tournament>(defaultTournament),[saving,setSaving]=useState(false),[note,setNote]=useState('');
 const [draft,setDraft]=useState({stage:'Quarter-final' as MatchStage,home:1,away:2,time:'18:00',court:'Court 1'});
 const [editors,setEditors]=useState<EditorRow[]>([]),[ownerEmail,setOwnerEmail]=useState(''),[newEmail,setNewEmail]=useState(''),[accessNote,setAccessNote]=useState('');
 useEffect(()=>{fetch('/api/tournament').then(r=>r.json()).then(setData).catch(()=>{})},[]);
 useEffect(()=>{if(isOwner)fetch('/api/editors').then(r=>r.json()).then(r=>{setEditors(r.editors??[]);setOwnerEmail(r.owner??'')}).catch(()=>{})},[isOwner]);
 const patchMatch=(id:number,key:string,value:string|number)=>setData(d=>({...d,matches:d.matches.map(m=>m.id===id?{...m,[key]:value}:m)}));
 const save=async()=>{setSaving(true);setNote('');const r=await fetch('/api/tournament',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});setSaving(false);setNote(r.ok?'Changes are live':'Could not save changes')};
 const addMatch=()=>{if(draft.home===draft.away){setNote('Choose two different teams');return}const id=Math.max(0,...data.matches.map(m=>m.id))+1;setData({...data,matches:[...data.matches,{id,...draft,homeScore:0,awayScore:0,sets:'',status:'scheduled'}]});setNote(`${draft.stage} match added. Publish changes when ready.`)};
 const removeMatch=(id:number)=>setData({...data,matches:data.matches.filter(m=>m.id!==id)});
 const addEditor=async()=>{setAccessNote('');const r=await fetch('/api/editors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:newEmail})});const body=await r.json();if(!r.ok){setAccessNote(body.error??'Could not add organizer');return}setEditors(body.editors);setOwnerEmail(body.owner);setNewEmail('');setAccessNote('Organizer authorized')};
 const removeEditor=async(email:string)=>{const r=await fetch('/api/editors',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const body=await r.json();if(r.ok)setEditors(body.editors);else setAccessNote(body.error??'Could not remove organizer')};
 return <main className="admin-shell"><header className="admin-head"><div><a href="/">← Public scoreboard</a><h1>Tournament control</h1><p>Signed in as {editor}</p></div><button onClick={save} disabled={saving}>{saving?'Publishing…':'Publish changes'}</button></header>{note&&<p className="notice">{note}</p>}
 <section className="settings"><label>Tournament name<input value={data.name} onChange={e=>setData({...data,name:e.target.value})}/></label><label>Dates<input value={data.dates} onChange={e=>setData({...data,dates:e.target.value})}/></label><label>Structure<select value={data.format} onChange={e=>setData({...data,format:e.target.value as Tournament['format']})}><option>Two groups</option><option>Round robin</option></select></label></section>
 <section className="admin-card add-match-card"><div className="section-title"><div><p className="kicker">NEXT STAGE</p><h2>Add a match</h2></div></div><p className="card-help">Add knockout matches whenever teams qualify. They appear publicly after you publish.</p><div className="new-match-grid"><label>Stage<select value={draft.stage} onChange={e=>setDraft({...draft,stage:e.target.value as MatchStage})}><option>Group stage</option><option>Quarter-final</option><option>Semi-final</option><option>Final</option><option>Friendly</option></select></label><label>Team 1<select value={draft.home} onChange={e=>setDraft({...draft,home:+e.target.value})}>{data.teams.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Team 2<select value={draft.away} onChange={e=>setDraft({...draft,away:+e.target.value})}>{data.teams.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Time<input type="time" value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Court<input value={draft.court} onChange={e=>setDraft({...draft,court:e.target.value})}/></label><button type="button" onClick={addMatch}>+ Add match</button></div></section>
 <section className="admin-match-area"><div className="section-title admin-matches-title"><div><p className="kicker">SCORE DESK</p><h2>Matches by stage</h2></div></div>{[...stageOrder].reverse().map(stage=>{const matches=data.matches.filter(m=>(m.stage??'Group stage')===stage).reverse();if(!matches.length)return null;return <section className="admin-card stage-admin-card" key={stage}><div className="stage-admin-head"><div><p className="kicker">TOURNAMENT STAGE</p><h3>{stage}</h3></div><span>{matches.length} {matches.length===1?'match':'matches'}</span></div>{matches.map(m=>{const home=data.teams.find(t=>t.id===m.home),away=data.teams.find(t=>t.id===m.away);return <div className="edit-match" key={m.id}><div><b>{home?.name}</b><small>{m.time} · {m.court}</small><b>{away?.name}</b></div><input aria-label="Home score" type="number" min="0" value={m.homeScore} onChange={e=>patchMatch(m.id,'homeScore',+e.target.value)}/><span>—</span><input aria-label="Away score" type="number" min="0" value={m.awayScore} onChange={e=>patchMatch(m.id,'awayScore',+e.target.value)}/><input aria-label="Set scores" value={m.sets} placeholder="6–3, 6–4" onChange={e=>patchMatch(m.id,'sets',e.target.value)}/><select value={m.status} onChange={e=>patchMatch(m.id,'status',e.target.value)}><option value="scheduled">Scheduled</option><option value="live">Live</option><option value="finished">Finished</option></select><button className="remove-match" type="button" onClick={()=>removeMatch(m.id)}>Remove</button></div>})}</section>})}</section>
 <section className="admin-card"><div className="section-title"><div><p className="kicker">REGISTRATION</p><h2>Teams & players</h2></div></div>{data.teams.map((t,i)=><div className="edit-team" key={t.id}><span>{i+1}</span><input value={t.name} onChange={e=>setData({...data,teams:data.teams.map(x=>x.id===t.id?{...x,name:e.target.value}:x)})}/><input value={t.players} onChange={e=>setData({...data,teams:data.teams.map(x=>x.id===t.id?{...x,players:e.target.value}:x)})}/></div>)}</section>
 {isOwner&&<section className="admin-card access-card"><div className="section-title"><div><p className="kicker">SECURITY</p><h2>Authorized organizers</h2></div><span className="owner-badge">OWNER ONLY</span></div><p className="card-help">Organizers sign in with ChatGPT using one of these email addresses. Only the owner can change this list.</p><div className="add-editor"><input type="email" value={newEmail} placeholder="organizer@gmail.com" onChange={e=>setNewEmail(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')addEditor()}}/><button type="button" onClick={addEditor}>Add organizer</button></div>{accessNote&&<p className="access-note">{accessNote}</p>}<div className="editor-list"><div className="editor-row owner-row"><span><b>{ownerEmail||editor}</b><small>Tournament owner</small></span><em>Owner</em></div>{editors.map(person=><div className="editor-row" key={person.email}><span><b>{person.email}</b><small>Authorized organizer</small></span><button type="button" onClick={()=>removeEditor(person.email)}>Remove</button></div>)}</div></section>}</main>
}
