'use client';
import { useEffect,useState } from 'react';
import { defaultTournament,stageOrder } from '@/lib/tournament';

export default function Home() {
  const [tournament,setTournament]=useState(defaultTournament);
  useEffect(()=>{const load=()=>fetch('/api/tournament',{cache:'no-store'}).then(r=>r.json()).then(setTournament).catch(()=>{});load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[]);
  const live=tournament.matches.find(m=>m.status==='live')??tournament.matches[0];
  const home=tournament.teams.find(t=>t.id===live?.home)??tournament.teams[0],away=tournament.teams.find(t=>t.id===live?.away)??tournament.teams[1];
  const standings=[...tournament.teams].sort((a,b)=>b.points-a.points).slice(0,4).map(t=>[t.name,t.players,t.played,t.won,t.points]);
  return <main className="shell">
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">P</span><span>CLUB PADEL</span></a><nav className="nav"><a className="active" href="#overview">Overview</a><a href="#matches">Matches</a><a href="#standings">Standings</a></nav><a className="admin-link" href="/admin">Manage tournament</a></header>
    <section className="hero" id="overview"><div><p className="eyebrow"><span className="live-dot" /> LIVE TOURNAMENT</p><h1>{tournament.name}</h1><p className="hero-copy">Follow every match, point and position live from the club courts.</p></div><div className="hero-stats"><div><strong>{tournament.teams.length}</strong><span>TEAMS</span></div><div><strong>{tournament.matches.length}</strong><span>MATCHES</span></div><div><strong>{new Set(tournament.matches.map(m=>m.court)).size}</strong><span>COURTS</span></div></div></section>
    <section className="content-grid">
      <div id="matches"><div className="section-title"><div><p className="kicker">ON COURT NOW</p><h2>Live matches</h2></div><span className="updated">Updated just now</span></div>
        <article className="live-card"><div className="match-meta"><span className="live-pill">{live?.status.toUpperCase()}</span><span>{live?.court} · {tournament.format}</span></div><div className="score-row"><div className="team"><span className="avatar lime">{home?.name.slice(0,2).toUpperCase()}</span><div><strong>{home?.name}</strong><small>{home?.players}</small></div></div><div className="score"><strong>{live?.homeScore}</strong><span>—</span><strong>{live?.awayScore}</strong><small>LIVE SCORE</small></div><div className="team away"><div><strong>{away?.name}</strong><small>{away?.players}</small></div><span className="avatar blue">{away?.name.slice(0,2).toUpperCase()}</span></div></div><div className="sets"><span>SETS</span><b>{live?.sets||'Not started'}</b></div></article>
        <div className="section-title upcoming"><div><p className="kicker">FULL TOURNAMENT</p><h2>Matches by stage</h2></div></div><div className="stage-stack" id="schedule">{[...stageOrder].reverse().map(stage=>{const matches=tournament.matches.filter(m=>(m.stage??'Group stage')===stage).reverse();if(!matches.length)return null;return <section className={`stage-box stage-${stage.toLowerCase().replaceAll(' ','-')}`} key={stage}><header><div><p className="kicker">TOURNAMENT STAGE</p><h3>{stage}</h3></div><span>{matches.length} {matches.length===1?'match':'matches'}</span></header><div className="match-list">{matches.map(m=>{const a=tournament.teams.find(t=>t.id===m.home),b=tournament.teams.find(t=>t.id===m.away);return <article key={m.id}><time>{m.time}<small>{m.court}</small></time><div><strong>{a?.name}</strong><small>{a?.players}</small></div><span>{m.status==='finished'?`${m.homeScore}–${m.awayScore}`:'VS'}</span><div className="right"><strong>{b?.name}</strong><small className={`status-${m.status}`}>{m.status.toUpperCase()}</small></div></article>})}</div></section>})}</div>
      </div>
      <aside className="standings-card" id="standings"><div className="section-title"><div><p className="kicker">GROUP STAGE</p><h2>Standings</h2></div><button>GROUP A⌄</button></div><div className="table-head"><span>TEAM</span><span>P</span><span>W</span><span>PTS</span></div>{standings.map((t,i)=><div className="standing" key={String(t[0])}><span className={`rank ${i===0?'first':''}`}>{i+1}</span><div><strong>{t[0]}</strong><small>{t[1]}</small></div><span>{t[2]}</span><span>{t[3]}</span><b>{t[4]}</b></div>)}<div className="legend"><span><i className="qualify"/> QUALIFIES</span><span><i/> ELIMINATED</span></div></aside>
    </section><footer><span>{tournament.name} · {tournament.dates}</span><span>Scores refresh automatically</span></footer>
  </main>;
}
